[package]
name = "lab4"
version = "0.1.0"
authors = ["Zaner256 <zaner256@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = {version="0.3.1", features=["rand"]}
rand = "0.7.3"
